import { i18n } from './i18n'

export const uiPort = 8081

// Where NextExplorer's or FileBrowser Quantum's data volume is mounted inside the MeTube container when
// the user routes downloads there (see main.ts + actions/downloadDestination).
export const nextexplorerMountpoint = '/mnt/nextexplorer'
export const filebrowserMountpoint = '/mnt/filebrowser'

// MeTube has no login of its own, so the StartOS reverse proxy enforces HTTP
// basic auth on the UI port. The username is always "admin"; the password is
// generated by the "Set Web UI Password" action.
export const uiUsername = 'admin'
export const randomPassword = { charset: 'a-z,A-Z,0-9', len: 32 }

export const trimSlashes = (path: string) => path.replace(/^\/+|\/+$/g, '')

// The NextExplorer location a subfolder lives in, which add-location creates.
export const locationOf = (subfolder: string) =>
  trimSlashes(subfolder).split('/')[0]

export const subfolderPattern = {
  regex: '(?!/)(?!(?:.*/)?\\.\\.(?:/.*)?$).+',
  description: i18n('Cannot start with a slash or contain a .. folder'),
}

// NextExplorer's own location-name rules (its utils.ts), applied to the first folder.
export const nextexplorerLocationPattern = {
  regex:
    '(?![.\\s])(?!(?:_[uU][sS][eE][rR][sS]|[pP][eE][rR][sS][oO][nN][aA][lL]|[sS][hH][aA][rR][eE]|[vV][oO][lL][uU][mM][eE][sS])(?:/|$))[^/]*[^/\\s](?:/.*)?',
  description: i18n(
    'The first folder is a NextExplorer location: it cannot start with a dot or a space, end with a space, or be _users, personal, share or volumes',
  ),
}
