export const uiPort = 8081

// Where File Browser's data volume is mounted inside the MeTube container when
// the user routes downloads there (see main.ts + actions/downloadDestination).
export const filebrowserMountpoint = '/mnt/filebrowser'

// MeTube has no login of its own, so the StartOS reverse proxy enforces HTTP
// basic auth on the UI port. The username is always "admin"; the password is
// generated by the "Set Web UI Password" action.
export const uiUsername = 'admin'
export const randomPassword = { charset: 'a-z,A-Z,0-9', len: 32 }
